# vim: set filetype=yaml shiftwidth=2 tabstop=2 expandtab shiftwidth :
---

# - name: "Update last operation"
#   asb_last_operation:
#     description: "0%: Starting"
#   when: in_cluster

- name: 'Set facts'
  set_fact:
    cluster: '{{ "openshift" if "openshift" in lookup("k8s", cluster_info="version") else "kubernetes" }}'
    uniqname: '{{ _apb_service_instance_id.split("-")[0] | lower }}'

- name: "Set flask-prometheus-ex objects state={{ state }}"
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', item.name) | from_yaml }}"
  when: item.apply | default(True)
  loop:
    - name: buildconfig.yml.j2
    - name: deploymentconfig.yml.j2
    - name: imagestream.yml.j2
#    - name: servicemonitor.yml.j2
    - name: service.yml.j2
    - name: route.yml.j2

- name: "start the buildconfig"
  shell: "oc start-build {{ app_name }}"
  # when: apb_action is present


# - name: "Update last operation"
#   asb_last_operation:
#     description: "100%: Done"
#   when: in_cluster
